# Site settings
title: John Stuifbergen
email: johnstuif+website@gmail.com
description: "This is a means to share some knowledge and experience I've picked up over the years and a way to share some of the craziness going on in my head."
baseurl: ""
url: "http://johnstuifbergen.com"
twitter_username: johnstuif
github_username:  johnstuif
timezone: CHICAGO

# Build settings
markdown: kramdown
permalink: pretty

exclude: [sass, layout.bmml]